### ISSUE TITLE
Update for SteamVR 1473196558

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Vive#21]
Looks like on all three platforms, the interface string `IVRSettings_001` in v1467410709 was replaced by `IVRSettings_002` in v1473196558. If

**Comment by mncharity** [comment]
Blocked on https://github.com/ValveSoftware/openvr/issues/276

**Comment by godbyk** [comment]
OpenVR version 1.0.3 is [now available](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.3) and includes the new Settings API.

**Comment by peroht** [comment]
Excellent, good with initial support.


-------- Originalmeddelande --------
Från: Kevin Godby <notifications@github.com> 
Datum: 2016-10-23  01:04  (GMT+01:00) 
Till: OSVR/OSVR-Vive <OSVR-Vive@noreply.github.com> 
Rubrik: Re: [OSVR/OSVR-Vive] Update for SteamVR 1473196558 (#21) 

OpenVR version 1.0.3 is now available and includes the new Settings API.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OSVR/OSVR-Vive","title":"OSVR/OSVR-Vive","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OSVR/OSVR-Vive"}},"updates":{"snippets":[{"icon":"PERSON","message":"@godbyk in #21: OpenVR version 1.0.3 is [now available](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.3) and includes the new Settings API."}],"action":{"name":"View Issue","url":"https://github.com/OSVR/OSVR-Vive/issues/21#issuecomment-255559287"}}}

**Comment by rpavlik** [comment]
Resolved in the latest OSVR-Vive merge.
